FROM tomcat:9.0

RUN mv /usr/local/tomcat/webapps.dist/* /usr/local/tomcat/webapps
COPY src/main/resources/tomcat-users.xml /usr/local/tomcat/conf
COPY src/main/resources/context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml
COPY target/demo-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps

CMD catalina.sh run